name: ci
on:
  workflow_dispatch: # allow manual trigger
  push:
  pull_request:
jobs:
  call-tf-reusable-workflow:
    uses: atrakic/terraform-test-workflow/.github/workflows/tf-reusable-workflow.yml@main
    with:
      working_directory: tests/tf
