name: ci
on:
  workflow_dispatch: # allow manual trigger
  push:
    paths:
      - 'tests/**'
      - '.github/workflows/ci.yml'
      - '.github/workflows/tf-reusable-workflow.yml'
  pull_request:
    paths:
      - 'tests/**'
      - '.github/workflows/ci.yml'
      - '.github/workflows/tf-reusable-workflow.yml'
jobs:
  call-tf-reusable-workflow:
    uses: atrakic/terraform-bootstrap/.github/workflows/terraform-test-workflow.yml@main
    with:
      working_directory: tests
